### ISSUE TITLE
not found error 

### ISSUE THREAD

**Issue by wilson2016** [joelnb/sofa#1]
NullAuthenticator()  DocumentMetadata  can't be found in Examples of  the project . how to deal with it?

**Comment by joelnb** [comment]
Glad to help. If you add this at the end of the main method from the second example it will retrieve the document it puts there and display the revision it gets when retrieving it (twice):

```go
    getDoc := &struct {
        sofa.DocumentMetadata
        Name string `json:"name"`
        Type string `json:"type"`
    }{}

    getRev, err := db.Get(getDoc, "fruit1", "")
    if err != nil {
        panic(err)
    }

    fmt.Println(getRev)
    fmt.Println(getDoc.Metadata().Rev)
```

When running this I get output like:

```console
$ go run issue.go                                       
1-0d4f963b2634b77ca5737ab8a774d2ab
1-0d4f963b2634b77ca5737ab8a774d2ab
1-0d4f963b2634b77ca5737ab8a774d2ab
```

**Comment by joelnb** [comment]
I am closing this as it doesn't seem to require any further changes to the code and I believe the initial issue is now solved.
