### ISSUE TITLE
How to call  /db/_find

### ISSUE THREAD

**Issue by nkev** [joelnb/sofa#12]
I couldn't find a way to unmarshal the "docs" array in the returned JSON from [/db/_find]( https://docs.couchdb.org/en/stable/api/database/find.html#api-db-find). Is this supported?

**Comment by joelnb** [comment]
There's not a proper way yet but I'd be happy to have a go at writing something. Have you already tried something to do this or did you just realise from the docs/code that it's not possible?

**Comment by nkev** [comment]
Thanks Joel. I initially wanted to create `foo.Create()` and `foo.Update()` methods to persist to CouchDB, but later realised I can actually create a single `foo.Save()` which does a `PUT` for both create and update. I just make sure I supply a `foo.DocumentMetadata.ID` if it is blank (i.e. if foo is new). Seems to work ok. Do you have any thoughts about this?
