### ISSUE TITLE
feed.Next()

### ISSUE THREAD

**Issue by nkev** [joelnb/sofa#13]
I'm getting the following error in CouchDB v3.1.1 MacOS:

`json: cannot unmarshal string into Go struct field ChangesFeedChange.seq of type int64`

on the line `feed.Next()`

```Go
feed := db.ContinuousChangesFeed(sofa.ChangesFeedParams{})
feed.Next()
```

If I change the data type of ChangesFeedChange.Seq in your `feed.go` file from int64 to a string, it works fine:

```Go
// ChangesFeedChange is a single change to a document in the database. One of
// more of these will be included in updates where any changes were actually made.
type ChangesFeedChange struct {
	Changes []struct {
		Rev string `json:"rev"`
	} `json:"changes"`
	Deleted bool   `json:"deleted"`
	ID      string `json:"id"`
	Seq     string  `json:"seq"`
}
```

Is this a bug or do you think making that change will break the code for earlier versions of CouchDB?

**Comment by joelnb** [comment]
Sadly this is a breaking change to the CouchDB API which means it's not quite as simple as just updating the type. I had a go at making the required changes and it seems to work but I don't love the implementation: https://github.com/joelnb/sofa/pull/14

Also it seems like this issue exists also on CouchDB 2. Are you only using version 3 or are you able to use version 2 without hitting this issue?

**Comment by nkev** [comment]
Thanks for looking at this. 

Wow, you've spent a lot of time on this, much appreciated.

I use version 3 only. I don't much like the versioned `NewConnection3 ` like methods either. Separating versions into packages seems to be a popular way to go recently, i.e. `github.com/joelnb/sofa/v1`, `github.com/joelnb/sofa/v2` and `github.com/joelnb/sofa/v3`. The different versions could pull common code off another common root package.

**Comment by joelnb** [comment]
Yeah the way you are suggesting is probably a better way to go than things are now - the current way results in too many ugly things like the `Database3` type included in that PR. I'll probably consider doing that but not sure when I will get the time.

Could you please link me to more info on the partition capabilities? I've not been doing the best job keeping up with the new features but I'm happy to add something if I can easily add tests for it & it doesn't require huge changes.

**Comment by nkev** [comment]
I can help with the versioning makeover. If you do `github.com/joelnb/sofa/v1`, I can can do V3 and keep it consistent with your code.

The partitioning feature was introduced in v3.0 and not only makes data modeling really easy but significantly increases performance. Think of it like a database within each database. 

For example, in pre V3 CouchDB, you could create a `content` CMS database  and establish a document key convention like `[pageID]-[contentID]`, e.g. `p01-c01` or `p01-section01`, `p01-summary`. You would then get all content for page1 by searching for all keys that start with `p01-`. This works fine, except that you are searching through the whole database, even with the default `id` index.

In v3 you can partition this database by pageID using a colon character, e.g. `p01:c01` or `p01:section01`, `p01:summary`. The most important thing here is that all documents in the partition (each page in this case) are **stored together**, which means you can search only **within** the partition, significantly increasing performance. You no longer need to search for all keys that start with `p01-`. There is new syntax to specify the partition and then search only inside of that:

```SH
http://localhost:5984/content/p01:summary                                 //super fast way to get a document
http://localhost:5984/content/_partition/p01/_all_docs?include_docs=true. //get all documents in a partition
http://localhost:5984/content/_partition/p01/_find?include_docs=true      //secondary index search within a partition
```

This is a game changer because lookups a super fast, even for secondary indexes, e.g. when using an indexed `type` property in your document. 

V3 docs on partitioning are here:
https://docs.couchdb.org/en/stable/partitioned-dbs/index.html

The paritioning feature is actually preparation for the upcoming CouchDB v4, which was developed in parallel with V3 and will likely be released this year.  It completely replaces the underlying Erlang based database engine with [Apples Foundation DB](https://www.youtube.com/watch?v=SjXyVZZFkBg) (this is a must-watch!). I've confirmed with the CouchDB devs that the syntax we use today won't change in V4, which is great. 

I really think CouchDB V4 will become hugely popular, especially in the Enterprise where scalability is still not super easy, like it is on CouchDB. Exciting times!
